create table CATEGORY
(
    CategoryID     int auto_increment
        primary key,
    CategoryGroup  varchar(10) null,
    CategoryName   varchar(30) null,
    CategoryLevel  int         null,
    CategoryParent int         null
);

INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (1, 'A', '디지털기기', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (2, 'A', 'TV/영상가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (3, 'A', 'TV', 3, 2);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (4, 'A', '미러링/스트리밍', 3, 2);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (5, 'A', 'TV악세서리', 3, 2);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (6, 'A', '빔/프로젝터/스크린', 3, 2);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (7, 'A', '냉장고', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (8, 'A', '일반냉장고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (9, 'A', '미니냉장고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (10, 'A', '김치냉장고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (11, 'A', '냉동고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (12, 'A', '전용냉장고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (13, 'A', '3/4도어냉장고', 3, 7);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (14, 'A', '세탁기/건조기', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (15, 'A', '세탁기건조기세트', 3, 14);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (16, 'A', '세탁기', 3, 14);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (17, 'A', '건조기', 3, 14);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (18, 'A', '의류관리기', 3, 14);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (19, 'A', '악세서리', 3, 14);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (20, 'A', '생활가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (21, 'A', '다리미/재봉/보풀', 3, 20);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (22, 'A', '도어록/비디오폰', 3, 20);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (23, 'A', '비데/온수기', 3, 20);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (24, 'A', '전동칫솔/살균기', 3, 20);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (25, 'A', '청소기', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (26, 'A', '먼지비움청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (27, 'A', '스틱청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (28, 'A', '진공청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (29, 'A', '로봇청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (30, 'A', '물걸레청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (31, 'A', '기타청소기', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (32, 'A', '필터/악세서리', 3, 25);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (33, 'A', '계절가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (34, 'A', '공기청정기', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (35, 'A', '선풍기', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (36, 'A', '에어컨', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (37, 'A', '제습기', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (38, 'A', '냉풍기', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (39, 'A', '모기/해충퇴치기', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (40, 'A', '가습기/에어워셔', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (41, 'A', '냉온수매트', 3, 33);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (42, 'A', '뷰티/헤어가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (43, 'A', '헤어드라이어', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (44, 'A', '고데기/매직기', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (45, 'A', '두피/헤어관리', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (46, 'A', '피부관리기기', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (47, 'A', '면도기/이발기', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (48, 'A', '제모기', 3, 42);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (49, 'A', '건강가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (50, 'A', '안마의자', 3, 49);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (51, 'A', '안마/찜질기', 3, 49);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (52, 'A', '구강가전', 3, 49);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (53, 'A', '의료기기', 3, 49);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (54, 'A', '살균/소독', 3, 49);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (55, 'A', '주방가전', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (56, 'A', '전기밥솥', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (57, 'A', '전자레인지', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (58, 'A', '오븐', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (59, 'A', '가스레인지', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (60, 'A', '식기세척/건조기', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (61, 'A', '믹서기', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (62, 'A', '커피머신', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (63, 'A', '전기포트', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (64, 'A', '튀김기', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (65, 'A', '토스터', 3, 55);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (66, 'A', '노트북', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (67, 'A', '삼성', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (68, 'A', 'LG전자', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (69, 'A', 'Apple', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (70, 'A', 'Lenovo', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (71, 'A', 'hp', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (72, 'A', 'msi', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (73, 'A', 'MicrosoftSurface', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (74, 'A', '한성컴퓨터', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (75, 'A', 'DELL', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (76, 'A', 'GIGABYTE', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (77, 'A', 'acer', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (78, 'A', 'intel', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (79, 'A', '기타 브랜드', 3, 66);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (80, 'A', '데스크탑', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (81, 'A', '브랜드PC', 3, 80);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (82, 'A', '일체형PC', 3, 80);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (83, 'A', '조립PC', 3, 80);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (84, 'A', '미니PC', 3, 80);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (85, 'A', '휴대폰', 3, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (86, 'A', 'Apple', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (87, 'A', '삼성전자', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (88, 'A', '갤럭시', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (89, 'A', '샤오미', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (90, 'A', '2G', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (91, 'A', '기타', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (92, 'A', '핸드폰 악세서리', 3, 85);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (93, 'A', '태블릿PC', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (94, 'A', '삼성', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (95, 'A', 'LG전자', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (96, 'A', 'Apple', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (97, 'A', 'Lenovo', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (98, 'A', '태클라스트', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (99, 'A', '아이뮤즈', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (100, 'A', '샤론6', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (101, 'A', 'EKASN', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (102, 'A', '머큐리', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (103, 'A', '악세서리', 3, 93);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (104, 'A', '스마트워치/밴드', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (105, 'A', '스마트워치', 3, 104);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (106, 'A', '스마트밴드', 3, 104);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (107, 'A', '악세서리', 3, 104);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (108, 'A', '게임', 2, 1);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (109, 'A', '게이밍노트북', 3, 108);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (110, 'A', '게이밍데스크탑', 3, 108);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (111, 'A', '게이밍모니터', 3, 108);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (112, 'B', '가구/인테리어', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (113, 'B', '가구 ', 2, 112);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (114, 'B', '소파', 3, 113);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (115, 'B', '침대', 3, 113);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (116, 'B', '테이블/의자', 3, 113);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (117, 'B', '인테리어', 2, 112);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (118, 'B', '디퓨저/방향제', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (119, 'B', '시계', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (120, 'B', '거울', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (121, 'B', '액자', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (122, 'B', '그림/사진', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (123, 'B', '시트지/스티커', 3, 117);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (124, 'C', '어린이/아기', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (125, 'C', '유아용품', 2, 124);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (126, 'C', '유아의류', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (127, 'C', '기저귀', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (128, 'C', '물티슈', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (129, 'C', '이유식', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (130, 'C', '분유', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (131, 'C', '장난감', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (132, 'C', '게임기', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (133, 'C', '기타 유아용품', 3, 125);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (134, 'C', '홈인테리어', 2, 124);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (135, 'C', '카페트', 3, 134);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (136, 'C', '세탁/청소용품', 3, 134);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (137, 'C', '유아가구', 3, 134);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (138, 'C', '유아침구', 3, 134);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (139, 'C', '안전용품', 3, 134);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (140, 'D', '패션', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (141, 'D', '여성의류', 2, 140);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (142, 'D', '상의', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (143, 'D', '원피스', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (144, 'D', '하의', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (145, 'D', '치마', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (146, 'D', '신발', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (147, 'D', '여성악세서리', 3, 141);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (148, 'D', '남성의류', 2, 140);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (149, 'D', '상의', 3, 148);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (150, 'D', '하의', 3, 148);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (151, 'D', '신발', 3, 148);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (152, 'D', '남성악세서리', 3, 148);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (153, 'D', '뷰티 ', 2, 140);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (154, 'D', '스킨케어', 3, 153);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (155, 'D', '메이크업', 3, 153);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (156, 'D', '향수', 3, 153);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (157, 'E', '스포츠/레저', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (158, 'E', '스포츠장비', 2, 157);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (159, 'E', '피트니스 장비', 3, 158);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (160, 'E', '캠핑장비', 3, 158);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (161, 'E', '자전거', 3, 158);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (162, 'E', '운동복', 2, 157);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (163, 'E', '기능성의류', 3, 162);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (164, 'E', '운동화', 3, 162);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (165, 'E', '수영복', 3, 162);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (166, 'F', '중고차/자동차', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (167, 'F', '중고차 ', 2, 166);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (168, 'F', '세단', 3, 167);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (169, 'F', 'SUV', 3, 167);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (170, 'F', '트럭', 3, 167);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (171, 'F', '부품/악세서리', 2, 166);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (172, 'F', '타이어', 3, 171);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (173, 'F', '휠', 3, 171);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (174, 'F', '전자장치', 3, 171);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (175, 'F', '외부 액세서리', 3, 171);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (176, 'G', '도서 및 미디어', 1, 0);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (177, 'G', '책', 2, 176);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (178, 'G', '소설', 3, 177);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (179, 'G', '논픽션', 3, 177);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (180, 'G', '아동도서', 3, 177);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (181, 'G', '기타도서', 3, 177);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (182, 'G', '영화 및 음악', 2, 176);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (183, 'G', 'DVD/블루레이', 3, 182);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (184, 'G', 'CD', 3, 182);
INSERT INTO dbtest.CATEGORY (CategoryID, CategoryGroup, CategoryName, CategoryLevel, CategoryParent) VALUES (185, 'G', '기타 악세서리', 3, 182);
