create table POST
(
    PostID      int          not null
        primary key,
    UserID      int          not null,
    TownID      int          null,
    PostTitle   varchar(100) not null,
    CategoryID  int          not null,
    PostCost    int          null,
    PostContent text         null,
    PostImage   text         null,
    Created     timestamp    not null,
    Updatedd    timestamp    null,
    Statuss     int          null,
    constraint POST_fk
        foreign key (UserID) references USER (UserID),
    constraint POST_fk2
        foreign key (CategoryID) references CATEGORY (CategoryID)
);

INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2001, 1028, 0, '게시물  2001/ 작성자 1028', 3022, 2907233, 'In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.', 'V3DD', '2022-08-28 11:20:00', '2022-09-30 11:20:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2002, 1041, 0, '게시물   2002/ 작성자 1041', 3006, 9510568, '“Whenever you feel like criticizing any one,” he told me, “just remember that all the people in this world haven’t had the advantages that you’ve had.”', '5R3N', '2022-11-24 11:07:00', '2022-12-18 11:07:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2003, 1037, 0, '게시물   2003/ 작성자 1037', 3021, 2300714, 'He didn’t say any more, but we’ve always been unusually communicative in a reserved way, and I understood that he meant a great deal more than that. In consequence, I’m inclined to reserve all judgments, a habit that has opened up many curious natures to me and also made me the victim of not a few veteran bores. The abnormal mind is quick to detect and attach itself to this quality when it appears in a normal person, and so it came about that in college I was unjustly accused of being a politician, because I was privy to the secret griefs of wild, unknown men. Most of the confidences were unsought ? frequently I have feigned sleep, preoccupation, or a hostile levity when I realized by some unmistakable sign that an intimate revelation was quivering on the horizon; for the intimate revelations of young men, or at least the terms in which they express them, are usually plagiaristic and marred by obvious suppressions. Reserving judgments is a matter of infinite hope. I am still a little afraid of missing something if I forget that, as my father snobbishly suggested, and I snobbishly repeat, a sense of the fundamental decencies is parcelled out unequally at birth.', 'TU2P', '2022-10-15 20:36:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2004, 1011, 0, '게시물   2004/ 작성자 1011', 3022, 9844032, 'And, after boasting this way of my tolerance, I come to the admission that it has a limit. Conduct may be founded on the hard rock or the wet marshes, but after a certain point I don’t care what it’s founded on. When I came back from the East last autumn I felt that I wanted the world to be in uniform and at a sort of moral attention forever; I wanted no more riotous excursions with privileged glimpses into the human heart. Only Gatsby, the man who gives his name to this book, was exempt from my reaction ? Gatsby, who represented everything for which I have an unaffected scorn. If personality is an unbroken series of successful gestures, then there was something gorgeous about him, some heightened sensitivity to the promises of life, as if he were related to one of those intricate machines that register earthquakes ten thousand miles away. This responsiveness had nothing to do with that flabby impressionability which is dignified under the name of the “creative temperament.”? it was an extraordinary gift for hope, a romantic readiness such as I have never found in any other person and which it is not likely I shall ever find again. No ? Gatsby turned out all right at the end; it is what preyed on Gatsby, what foul dust floated in the wake of his dreams that temporarily closed out my interest in the abortive sorrows and short-winded elations of men.', 'G32X', '2022-05-01 04:38:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2005, 1003, 0, '게시물   2005/ 작성자 1003', 3017, 6186936, 'My family have been prominent, well-to-do people in this Middle Western city for three generations. The Carraways are something of a clan, and we have a tradition that we’re descended from the Dukes of Buccleuch, but the actual founder of my line was my grandfather’s brother, who came here in fifty-one, sent a substitute to the Civil War, and started the wholesale hardware business that my father carries on to-day.', '45I8', '2022-01-27 18:55:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2006, 1032, 0, '게시물   2006/ 작성자 1032', 3021, 8228169, 'I never saw this great-uncle, but I’m supposed to look like him ? with special reference to the rather hard-boiled painting that hangs in father’s office. I graduated from New Haven in 1915, just a quarter of a century after my father, and a little later I participated in that delayed Teutonic migration known as the Great War. I enjoyed the counter-raid so thoroughly that I came back restless. Instead of being the warm centre of the world, the Middle West now seemed like the ragged edge of the universe ? so I decided to go East and learn the bond business. Everybody I knew was in the bond business, so I supposed it could support one more single man. All my aunts and uncles talked it over as if they were choosing a prep school for me, and finally said, “Why ? ye ? es,” with very grave, hesitant faces. Father agreed to finance me for a year, and after various delays I came East, permanently, I thought, in the spring of twenty-two.', '10EN', '2022-10-07 08:47:00', '2022-10-20 08:47:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2007, 1003, 0, '게시물   2007/ 작성자 1003', 3003, 5246384, 'The practical thing was to find rooms in the city, but it was a warm season, and I had just left a country of wide lawns and friendly trees, so when a young man at the office suggested that we take a house together in a commuting town, it sounded like a great idea. He found the house, a weather-beaten cardboard bungalow at eighty a month, but at the last minute the firm ordered him to Washington, and I went out to the country alone. I had a dog ? at least I had him for a few days until he ran away ? and an old Dodge and a Finnish woman, who made my bed and cooked breakfast and muttered Finnish wisdom to herself over the electric stove.', 'V01B', '2022-01-12 18:55:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2008, 1028, 0, '게시물   2008/ 작성자 1028', 3014, 3063563, 'It was lonely for a day or so until one morning some man, more recently arrived than I, stopped me on the road.', '4K04', '2022-09-01 11:20:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2009, 1027, 0, '게시물   2009/ 작성자 1027', 3014, 0, '“How do you get to West Egg village?” he asked helplessly.', '63R5', '2022-08-22 17:49:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2010, 1031, 0, '게시물   2010/ 작성자 1031', 3004, 1678758, 'I told him. And as I walked on I was lonely no longer. I was a guide, a pathfinder, an original settler. He had casually conferred on me the freedom of the neighborhood.', '61BE', '2022-09-21 02:32:00', '2022-09-22 02:32:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2011, 1022, 0, '게시물   2011/ 작성자 1022', 3003, 1171399, 'And so with the sunshine and the great bursts of leaves growing on the trees, just as things grow in fast movies, I had that familiar conviction that life was beginning over again with the summer.', 'SA0N', '2022-06-16 06:30:00', '2022-07-14 06:30:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2012, 1030, 0, '게시물   2012/ 작성자 1030', 3016, 4396004, 'There was so much to read, for one thing, and so much fine health to be pulled down out of the young breath-giving air. I bought a dozen volumes on banking and credit and investment securities, and they stood on my shelf in red and gold like new money from the mint, promising to unfold the shining secrets that only Midas and Morgan and Maecenas knew. And I had the high intention of reading many other books besides. I was rather literary in college ? one year I wrote a series of very solemn and obvious editorials for the “Yale News.”? and now I was going to bring back all such things into my life and become again that most limited of all specialists, the “well-rounded man.” This isn’t just an epigram ? life is much more successfully looked at from a single window, after all.', 'P651', '2022-09-09 18:29:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2013, 1049, 0, '게시물   2013/ 작성자 1049', 3014, 4907897, 'It was a matter of chance that I should have rented a house in one of the strangest communities in North America. It was on that slender riotous island which extends itself due east of New York ? and where there are, among other natural curiosities, two unusual formations of land. Twenty miles from the city a pair of enormous eggs, identical in contour and separated only by a courtesy bay, jut out into the most domesticated body of salt water in the Western hemisphere, the great wet barnyard of Long Island Sound. They are not perfect ovals ? like the egg in the Columbus story, they are both crushed flat at the contact end ? but their physical resemblance must be a source of perpetual confusion to the gulls that fly overhead. To the wingless a more arresting phenomenon is their dissimilarity in every particular except shape and size.', '1751', '2023-02-26 22:38:00', '2023-03-11 22:38:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2014, 1036, 0, '게시물   2014/ 작성자 1036', 3020, 5042760, 'I lived at West Egg, the ? well, the less fashionable of the two, though this is a most superficial tag to express the bizarre and not a little sinister contrast between them. My house was at the very tip of the egg, only fifty yards from the Sound, and squeezed between two huge places that rented for twelve or fifteen thousand a season. The one on my right was a colossal affair by any standard ? it was a factual imitation of some Hotel de Ville in Normandy, with a tower on one side, spanking new under a thin beard of raw ivy, and a marble swimming pool, and more than forty acres of lawn and garden. It was Gatsby’s mansion. Or, rather, as I didn’t know Mr. Gatsby, it was a mansion inhabited by a gentleman of that name. My own house was an eyesore, but it was a small eyesore, and it had been overlooked, so I had a view of the water, a partial view of my neighbor’s lawn, and the consoling proximity of millionaires ? all for eighty dollars a month.', 'I82I', '2022-10-26 23:11:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2015, 1031, 0, '게시물   2015/ 작성자 1031', 3019, 277730, 'Across the courtesy bay the white palaces of fashionable East Egg glittered along the water, and the history of the summer really begins on the evening I drove over there to have dinner with the Tom Buchanans. Daisy was my second cousin once removed, and I’d known Tom in college. And just after the war I spent two days with them in Chicago.', 'A171', '2022-10-04 02:32:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2016, 1035, 0, '게시물   2016/ 작성자 1035', 3022, 9843001, 'Her husband, among various physical accomplishments, had been one of the most powerful ends that ever played football at New Haven ? a national figure in a way, one of those men who reach such an acute limited excellence at twenty-one that everything afterward savors of anti-climax. His family were enormously wealthy ? even in college his freedom with money was a matter for reproach ? but now he’d left Chicago and come East in a fashion that rather took your breath away: for instance, he’d brought down a string of polo ponies from Lake Forest. It was hard to realize that a man in my own generation was wealthy enough to do that.', 'C43R', '2022-10-02 20:44:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2017, 1001, 0, '게시물   2017/ 작성자 1001', 3019, 1997625, 'Why they came East I don’t know. They had spent a year in France for no particular reason, and then drifted here and there unrestfully wherever people played polo and were rich together. This was a permanent move, said Daisy over the telephone, but I didn’t believe it ? I had no sight into Daisy’s heart, but I felt that Tom would drift on forever seeking, a little wistfully, for the dramatic turbulence of some irrecoverable football game.', 'E44A', '2022-01-03 15:17:00', '2022-01-15 15:17:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2018, 1039, 0, '게시물   2018/ 작성자 1039', 3004, 2900925, 'And so it happened that on a warm windy evening I drove over to East Egg to see two old friends whom I scarcely knew at all. Their house was even more elaborate than I expected, a cheerful red-and-white Georgian Colonial mansion, overlooking the bay. The lawn started at the beach and ran toward the front door for a quarter of a mile, jumping over sun-dials and brick walks and burning gardens ? finally when it reached the house drifting up the side in bright vines as though from the momentum of its run. The front was broken by a line of French windows, glowing now with reflected gold and wide open to the warm windy afternoon, and Tom Buchanan in riding clothes was standing with his legs apart on the front porch.', 'PYM5', '2022-11-25 21:08:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2019, 1007, 0, '게시물   2019/ 작성자 1007', 3014, 9777982, 'He had changed since his New Haven years. Now he was a sturdy straw-haired man of thirty with a rather hard mouth and a supercilious manner. Two shining arrogant eyes had established dominance over his face and gave him the appearance of always leaning aggressively forward. Not even the effeminate swank of his riding clothes could hide the enormous power of that body ? he seemed to fill those glistening boots until he strained the top lacing, and you could see a great pack of muscle shifting when his shoulder moved under his thin coat. It was a body capable of enormous leverage ? a cruel body.', '7TRW', '2022-02-17 05:36:00', '2022-03-19 05:36:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2020, 1009, 0, '게시물   2020/ 작성자 1009', 3011, 8098479, 'His speaking voice, a gruff husky tenor, added to the impression of fractiousness he conveyed. There was a touch of paternal contempt in it, even toward people he liked ? and there were men at New Haven who had hated his guts.', 'ECX0', '2022-03-27 07:29:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2021, 1037, 0, '게시물   2021/ 작성자 1037', 3013, 31795, '“Now, don’t think my opinion on these matters is final,” he seemed to say, “just because I’m stronger and more of a man than you are.” We were in the same senior society, and while we were never intimate I always had the impression that he approved of me and wanted me to like him with some harsh, defiant wistfulness of his own.', '8D2R', '2022-10-20 20:36:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2022, 1029, 0, '게시물   2022/ 작성자 1029', 3011, 9918986, 'We talked for a few minutes on the sunny porch.', 'A734', '2022-08-21 05:26:00', '2022-09-01 05:26:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2023, 1034, 0, '게시물   2023/ 작성자 1034', 3003, 7872816, '“I’ve got a nice place here,” he said, his eyes flashing about restlessly.', 'E3IJ', '2022-10-11 12:44:00', '2022-10-21 12:44:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2024, 1011, 0, '게시물   2024/ 작성자 1011', 3016, 4765499, 'Turning me around by one arm, he moved a broad flat hand along the front vista, including in its sweep a sunken Italian garden, a half acre of deep, pungent roses, and a snub-nosed motor-boat that bumped the tide offshore.', '1M02', '2022-04-12 04:38:00', '2022-04-16 04:38:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2025, 1038, 0, '게시물   2025/ 작성자 1038', 3014, 4712244, '“It belonged to Demaine, the oil man.” He turned me around again, politely and abruptly. “We’ll go inside.”', 'M024', '2022-11-11 14:00:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2026, 1016, 0, '게시물   2026/ 작성자 1016', 3022, 7078547, 'We walked through a high hallway into a bright rosy-colored space, fragilely bound into the house by French windows at either end. The windows were ajar and gleaming white against the fresh grass outside that seemed to grow a little way into the house. A breeze blew through the room, blew curtains in at one end and out the other like pale flags, twisting them up toward the frosted wedding-cake of the ceiling, and then rippled over the wine-colored rug, making a shadow on it as wind does on the sea.', 'SMO4', '2022-05-22 07:20:00', '2022-06-10 07:20:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2027, 1004, 0, '게시물   2027/ 작성자 1004', 3014, 8447426, 'The only completely stationary object in the room was an enormous couch on which two young women were buoyed up as though upon an anchored balloon. They were both in white, and their dresses were rippling and fluttering as if they had just been blown back in after a short flight around the house. I must have stood for a few moments listening to the whip and snap of the curtains and the groan of a picture on the wall. Then there was a boom as Tom Buchanan shut the rear windows and the caught wind died out about the room, and the curtains and the rugs and the two young women ballooned slowly to the floor.', 'CUJ7', '2022-02-06 20:46:00', '2022-02-26 20:46:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2028, 1002, 0, '게시물   2028/ 작성자 1002', 3005, 2819578, 'The younger of the two was a stranger to me. She was extended full length at her end of the divan, completely motionless, and with her chin raised a little, as if she were balancing something on it which was quite likely to fall. If she saw me out of the corner of her eyes she gave no hint of it ? indeed, I was almost surprised into murmuring an apology for having disturbed her by coming in.', 'O6HJ', '2022-01-17 10:39:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2029, 1002, 0, '게시물   2029/ 작성자 1002', 3018, 411497, 'The other girl, Daisy, made an attempt to rise ? she leaned slightly forward with a conscientious expression ? then she laughed, an absurd, charming little laugh, and I laughed too and came forward into the room.', 'C8MQ', '2022-01-25 10:39:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2030, 1015, 0, '게시물   2030/ 작성자 1015', 3020, 5550462, '“I’m p-paralyzed with happiness.” She laughed again, as if she said something very witty, and held my hand for a moment, looking up into my face, promising that there was no one in the world she so much wanted to see. That was a way she had. She hinted in a murmur that the surname of the balancing girl was Baker. (I’ve heard it said that Daisy’s murmur was only to make people lean toward her; an irrelevant criticism that made it no less charming.)', '378K', '2022-05-23 00:22:00', '2022-05-27 00:22:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2031, 1010, 0, '게시물   2031/ 작성자 1010', 3016, 2999797, 'At any rate, Miss Baker’s lips fluttered, she nodded at me almost imperceptibly, and then quickly tipped her head back again ? the object she was balancing had obviously tottered a little and given her something of a fright. Again a sort of apology arose to my lips. Almost any exhibition of complete self-sufficiency draws a stunned tribute from me.', '1J82', '2022-04-10 18:33:00', '2022-04-29 18:33:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2032, 1020, 0, '게시물   2032/ 작성자 1020', 3020, 5814140, 'I looked back at my cousin, who began to ask me questions in her low, thrilling voice. It was the kind of voice that the ear follows up and down, as if each speech is an arrangement of notes that will never be played again. Her face was sad and lovely with bright things in it, bright eyes and a bright passionate mouth, but there was an excitement in her voice that men who had cared for her found difficult to forget: a singing compulsion, a whispered “Listen,” a promise that she had done gay, exciting things just a while since and that there were gay, exciting things hovering in the next hour.', 'X3OT', '2022-06-11 19:11:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2033, 1031, 0, '게시물   2033/ 작성자 1031', 3013, 2068530, 'I told her how I had stopped off in Chicago for a day on my way East, and how a dozen people had sent their love through me.', '6GM4', '2022-09-22 02:32:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2034, 1012, 0, '게시물   2034/ 작성자 1012', 3015, 3246407, '“Do they miss me?” she cried ecstatically.', 'JCQO', '2022-04-30 01:01:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2035, 1040, 0, '게시물   2035/ 작성자 1040', 3018, 9956111, '“The whole town is desolate. All the cars have the left rear wheel painted black as a mourning wreath, and there’s a persistent wail all night along the north shore.”', 'YB88', '2022-12-10 13:53:00', '2022-12-25 13:53:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2036, 1030, 0, '게시물   2036/ 작성자 1030', 3010, 7794458, '“How gorgeous! Let’s go back, Tom. To-morrow!” Then she added irrelevantly: “You ought to see the baby.”', 'G4PO', '2022-09-07 18:29:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2037, 1008, 0, '게시물   2037/ 작성자 1008', 3019, 5231681, '“I’d like to.”', '323H', '2022-03-02 04:40:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2038, 1042, 0, '게시물   2038/ 작성자 1042', 3005, 3586309, '“She’s asleep. She’s three years old. Haven’t you ever seen her?”', 'HV3G', '2022-12-17 01:52:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2039, 1045, 0, '게시물   2039/ 작성자 1045', 3004, 9233683, '“Never.”', '72X8', '2023-01-28 08:22:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2040, 1030, 0, '게시물   2040/ 작성자 1030', 3021, 7919677, '“Well, you ought to see her. She’s ??”', 'L4VR', '2022-08-30 18:29:00', '2022-09-20 18:29:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2041, 1003, 0, '게시물   2041/ 작성자 1003', 3020, 3110144, 'Tom Buchanan, who had been hovering restlessly about the room, stopped and rested his hand on my shoulder.', 'N668', '2022-01-21 18:55:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2042, 1006, 0, '게시물   2042/ 작성자 1006', 3011, 2083726, '“What you doing, Nick?”', 'P4PD', '2022-03-01 18:26:00', '2022-03-17 18:26:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2043, 1009, 0, '게시물   2043/ 작성자 1009', 3019, 1679451, '“I’m a bond man.”', '8G83', '2022-03-08 07:29:00', '2022-04-04 07:29:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2044, 1033, 0, '게시물   2044/ 작성자 1033', 3011, 8388172, '“Who with?”', 'KQD3', '2022-09-25 22:07:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2045, 1010, 0, '게시물   2045/ 작성자 1010', 3020, 7044232, 'I told him.', 'IC1Y', '2022-04-03 18:33:00', '2022-04-11 18:33:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2046, 1020, 0, '게시물   2046/ 작성자 1020', 3006, 0, '“Never heard of them,” he remarked decisively.', 'N82T', '2022-06-19 19:11:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2047, 1045, 0, '게시물   2047/ 작성자 1045', 3004, 8842057, 'This annoyed me.', '1EVN', '2023-02-08 08:22:00', '0000-00-00 00:00:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2048, 1008, 0, '게시물   2048/ 작성자 1008', 3009, 1419745, '“You will,” I answered shortly. “You will if you stay in the East.”', 'QIOB', '2022-03-20 04:40:00', '2022-04-05 04:40:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2049, 1018, 0, '게시물   2049/ 작성자 1018', 3017, 3415967, '“Oh, I’ll stay in the East, don’t you worry,” he said, glancing at Daisy and then back at me, as if he were alert for something more. “I’d be a God damned fool to live anywhere else.”', 'J8E0', '2022-06-02 06:44:00', '2022-06-26 06:44:00', 0);
INSERT INTO dbtest.POST (PostID, UserID, TownID, PostTitle, CategoryID, PostCost, PostContent, PostImage, Created, Updatedd, Statuss) VALUES (2050, 1001, 0, '게시물   2050/ 작성자 1001', 3001, 5333603, 'At this point Miss Baker said: “Absolutely!” with such suddenness that I started ? it was the first word she uttered since I came into the room. Evidently it surprised her as much as it did me, for she yawned and with a series of rapid, deft movements stood up into the room.', '3366', '2022-01-27 15:17:00', '0000-00-00 00:00:00', 0);
